#!/usr/bin/env sh
set -e

SERVER_CONFIG_PATH="${SERVER_CONFIG_PATH:-/etc/nginx/nginx.conf}";

NODE_PORT="${NODE_PORT:-3000}";
NODE_HOST="${NODE_HOST:-app}";
NODE_UPSTREAM_PARAMS="${NODE_UPSTREAM_PARAMS:-max_fails=3 fail_timeout=30s}";
ROOT_DIR="${ROOT_DIR:-/usr/share/nginx/html}";
VIRTUAL_HOST="${VIRTUAL_HOST:-_}";
ADDITIONAL_NODE_HOSTS="${ADDITIONAL_NODE_HOSTS:-# Additional NODE hosts not passed}";

sed -i "s#%NODE_PORT%#${NODE_PORT}#g" "$SERVER_CONFIG_PATH";
sed -i "s#%NODE_HOST%#${NODE_HOST}#g" "$SERVER_CONFIG_PATH";
sed -i "s#%NODE_UPSTREAM_PARAMS%#${NODE_UPSTREAM_PARAMS}#g" "$SERVER_CONFIG_PATH";
sed -i "s#%ROOT_DIR%#${ROOT_DIR}#g" "$SERVER_CONFIG_PATH";
sed -i "s#%VIRTUAL_HOST%#${VIRTUAL_HOST}#g" "$SERVER_CONFIG_PATH";
sed -i "s^%ADDITIONAL_NODE_HOSTS%^${ADDITIONAL_NODE_HOSTS}^g" "$SERVER_CONFIG_PATH";

exec "$@";
