#!/usr/bin/env sh
set -e

SERVER_CONFIG_PATH="${SERVER_CONFIG_PATH:-/etc/nginx/nginx.conf}";

REMOTE_PORT="${REMOTE_PORT:-3000}";
REMOTE_HOST="${REMOTE_HOST:-app}";
REMOTE_UPSTREAM_PARAMS="${REMOTE_UPSTREAM_PARAMS:-max_fails=3 fail_timeout=30s}";
ROOT_DIR="${ROOT_DIR:-/usr/share/nginx/html}";
VIRTUAL_HOST="${VIRTUAL_HOST:-_}";
ADDITIONAL_REMOTE_HOSTS="${ADDITIONAL_REMOTE_HOSTS:-# Additional NODE hosts not passed}";

sed -i "s#%REMOTE_PORT%#${REMOTE_PORT}#g" "$SERVER_CONFIG_PATH";
sed -i "s#%REMOTE_HOST%#${REMOTE_HOST}#g" "$SERVER_CONFIG_PATH";
sed -i "s#%REMOTE_UPSTREAM_PARAMS%#${REMOTE_UPSTREAM_PARAMS}#g" "$SERVER_CONFIG_PATH";
sed -i "s#%ROOT_DIR%#${ROOT_DIR}#g" "$SERVER_CONFIG_PATH";
sed -i "s#%VIRTUAL_HOST%#${VIRTUAL_HOST}#g" "$SERVER_CONFIG_PATH";
sed -i "s^%ADDITIONAL_REMOTE_HOSTS%^${ADDITIONAL_REMOTE_HOSTS}^g" "$SERVER_CONFIG_PATH";

exec "$@";
